#!/usr/bin/env python3
"""Convert SVG logo to bitfield C array for the ST7735 display."""

import sys
import io
import cairosvg
from PIL import Image


def svg_to_logo(svg_path, out_path, size=56, color=(255, 191, 0)):
    # Read SVG and replace CSS variables with explicit colors
    with open(svg_path) as f:
        svg_text = f.read()
    svg_text = svg_text.replace("fill='currentColor'", "fill='white'")
    svg_text = svg_text.replace("fill='var(--bg)'", "fill='black'")

    # Render SVG to PNG in memory
    png_data = cairosvg.svg2png(
        bytestring=svg_text.encode(),
        output_width=size,
        output_height=size,
        background_color="black",
    )
    img = Image.open(io.BytesIO(png_data)).convert("RGB")

    # Compute RGB565 color for reference (not used in output)
    r16 = (color[0] >> 3) << 11
    g16 = (color[1] >> 2) << 5
    b16 = color[2] >> 3
    fg_565 = r16 | g16 | b16

    # Extract foreground pixels (1 = amber, 0 = black)
    bits = []
    for y in range(img.height):
        for x in range(img.width):
            r, g, b = img.getpixel((x, y))
            lum = (r * 299 + g * 587 + b * 114) // 1000
            bits.append(1 if lum > 80 else 0)

    # Pack bits into bytes, MSB-first (bit 7 of byte 0 = pixel 0)
    bytes_data = []
    for byte_idx in range((len(bits) + 7) // 8):
        byte_val = 0
        for bit_idx in range(8):
            pixel_idx = byte_idx * 8 + bit_idx
            if pixel_idx < len(bits) and bits[pixel_idx]:
                byte_val |= (1 << (7 - bit_idx))
        bytes_data.append(byte_val)

    with open(out_path, "w") as f:
        f.write("// Auto-generated by scripts/svg_to_logo.py — do not edit\n")
        f.write('#include "logo_bits.h"\n\n')
        f.write("const uint8_t g_logo_bits[LOGO_BITS_LEN] = {\n")
        for i, byte_val in enumerate(bytes_data):
            if i % 12 == 0:
                f.write("    ")
            f.write(f"0x{byte_val:02X},")
            if i % 12 == 11 or i == len(bytes_data) - 1:
                f.write("\n")
            else:
                f.write(" ")
        f.write("};\n")

    fg_count = sum(bits)
    print(f"Generated {out_path}: {size}x{size} = {len(bits)} pixels "
          f"({fg_count} visible, {len(bytes_data)} bytes, color=0x{fg_565:04X})")


if __name__ == "__main__":
    svg = sys.argv[1] if len(sys.argv) > 1 else "components/http_server/logo.svg"
    out = sys.argv[2] if len(sys.argv) > 2 else "components/display/src/logo_bits.c"
    size = int(sys.argv[3]) if len(sys.argv) > 3 else 56
    svg_to_logo(svg, out, size)
